version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  test:
    docker:
      - image: circleci/node:12.14.1
        environment:
          DATABASE_USER: postgres
          DATABASE_PASSWORD: password
          DATABASE_NAME: todoist_clone_test
      - image: circleci/postgres:12.3
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: todoist_clone_test
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install --frozen-lockfile
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: yarn ci:test
      - store_artifacts:
          path: coverage
  build:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install --frozen-lockfile
      - run: yarn build

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build
